services:
  postgres:
    image: postgres:16-alpine
    container_name: telemetry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry-dev-2026
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telemetry -d telemetry"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: telemetry-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: telemetry
      RABBITMQ_DEFAULT_PASS: telemetry-dev-2026
      
  redis:
    image: redis:7-alpine
    container_name: telemetry-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  ingestion-api:
    build:
      context: ..
      dockerfile: src/Telemetry.Ingestion.Api/Dockerfile
    image: telemetry-ingestion-api:dev
    container_name: telemetry-ingestion-api
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: telemetry
      RabbitMq__Password: telemetry-dev-2026
      Redis__ConnectionString: "redis:6379"
    ports:
      - "8080:8080"

  worker:
    build:
      context: ..
      dockerfile: src/Telemetry.Worker/Dockerfile
    image: telemetry-worker:dev
    container_name: telemetry-worker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      Database__ConnectionString: "Host=postgres;Database=telemetry;Username=telemetry;Password=telemetry-dev-2026"
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: telemetry
      RabbitMq__Password: telemetry-dev-2026


volumes:
  postgres-data:
  rabbitmq-data:
  redis-data: